apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-pull 
  description: Secure Supply Chain Example for Go Runtime http based application with advanced continuous integration pipeline covering building, CVE scanning, security scanning, signatures,  attestations, SLSA provenance and SBOM along with Gitops-based continuous deployment   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:
    # ArgoCD apps from this template used rhtap-gitops as the grouping
    argocd/app-selector: rhtap/gitops=test-pull
    backstage.io/kubernetes-id: test-pull 
    backstage.io/techdocs-ref: dir:.
    dev.azure.com/project-repo: prietyc123-qe-org/test-pull
    dev.azure.com/project: shared-public
    dev.azure.com/build-definition: prietyc123-qe-org.test-pull
    quay.io/repository-slug: rhtap_qe/private_repo
  tags: ["go", "sscs", "sbom", "acs"] 
spec:
  type: service
  owner: user:guest 
  lifecycle: experimental
 